spring:
  application:
    name: 2025capstone

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/capstone?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root # 나중에 실제 환경에서 변경해주시면 됩니다.
    password: 0IzRxaAlqqxNCYg # 나중에 실제 환경에서 변경해주시면 됩니다.

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: never
      data-locations: classpath:data.sql

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  resources:
    static-locations: classpath:/static/
    add-mappings: true
    cache:
      period: 0

server:
  port: 8080

security:
  jwt:
    token:
      secret-key: authlakdjfalskdfjlaksdfjlkasdnfalskdfnlakqwiuerbwqieufbasidubf
      expire-length : 7200000000000

app:
  upload:
    dir: ${user.home}/Desktop
    image: ${user.home}/Desktop/uploads/images
    video: ${user.home}/Desktop/uploads/videos
    customVideo : ${user.home}/Desktop/uploads/videos/custom
    audio: ${user.home}/Desktop/uploads/audios
  python-server:
    url: http://localhost:5001  # 파이썬 서버 URL (필요시 변경)



